### ISSUE TITLE
Tag a new release since the current package is broken

### ISSUE THREAD

**Issue by ergonlogic** [php-tuf/composer-integration#124]
The current release (0.0.3) fails on install:

> $ composer require php-tuf/composer-integration
> [...]
> Fatal error: Declaration of Tuf\ComposerIntegration\TufValidatedComposerRepository::configurePackageTransportOptions(Composer\Package\PackageInterface $package) must be compatible with Composer\Repository\ComposerRepository::configurePackageTransportOptions(Composer\Package\PackageInterface $package): void in /var/www/html/vendor/php-tuf/composer-integration/src/TufValidatedComposerRepository.php on line 131
> Composer [require php-tuf/composer-integration] failed, composer command failed: exit status 255. stderr=

The underlying bug appears to have already been fixed on `main`. So just adding a new tag should make default installs work.

In the meantime: `composer require php-tuf/composer-integration:dev-main`

**Comment by phenaproxima** [comment]
No problem; I've tagged [1.0.0-alpha12](https://github.com/php-tuf/composer-integration/releases/tag/1.0.0-alpha12). @tedbow has not yet reviewed #120, which is the only change of note in this release, but if there are flaws in that code we will either fix them or revert it outright.
