### ISSUE TITLE
Distinguish between Composer metadata and TUF metadata in method names, comments, etc.

### ISSUE THREAD

**Issue by ergonlogic** [php-tuf/composer-integration#35]
Throughout the Composer plugin we're mostly referring to Composer package metadata. However, "metadata" is overloaded in the context of TUF. I think it'd be kind to other developers to make the distinction more explicit. Here's an example:

```
    /**
     * Reacts before metadata is downloaded.
     *
     * @param PreFileDownloadEvent $event
     *   The event object.
     */
    public function prepareMetadata(PreFileDownloadEvent $event): void
```

"Reacts before Composer repository and package metadata is downloaded" and `prepareComposerMetadata()` would help to avoid confusion.

**Comment by phenaproxima** [comment]
+1. If you file a PR, I'll merge it!
