### ISSUE TITLE
Document plugin expectations for Composer repository maintainers

### ISSUE THREAD

**Issue by phenaproxima** [php-tuf/composer-integration#54]
This plugin has expectations about how a Composer repository's TUF integration is set up. For example:

* All targets have to be in the `/targets` subdirectory.
* All metadata has to be in the `/metadata` subdirectory.
* Downloadable packages signed by TUF must always be identified by a key in the pattern of `VENDOR/NAME/NORMALIZED_VERSION`.
* All Composer package metadata is expected to be signed by TUF, and their key is expected to be their path relative to `/targets`.
* All downloadable packages in the repository are expected to be signed by TUF, regardless of where they _physically_ come from (i.e., URL doesn't matter as long as the target key is consistent and the hashes of the downloaded file match what TUF knows).
* The plugin expects TUF to know ahead of time the size, in bytes, of all downloadable packages.
* The repository maintainer must provide trusted root metadata to consumers, to bootstrap the chain of trust, and that file must be named in a specific way and be in a specific place.

...and possibly other stuff.

All of these things should be clearly documented, either in the wiki of this repository, or in a Markdown file. Since this could reasonably count as "API", this task should block a beta release of the plugin.

**Comment by phenaproxima** [comment]
Looping in @ergonlogic.

**Comment by phenaproxima** [comment]
Not to mention @tedbow, @hestenet, @davidstrauss, @effulgentsia, and @xjm.

**Comment by phenaproxima** [comment]
This may also be relevant for @ryanaslett.

**Comment by davidstrauss** [comment]
These all seem to be reasonable conventions, and I agree that we should document them to make them explicit.

**Comment by phenaproxima** [comment]
I've documented all of this in the wiki.
