### ISSUE TITLE
TUF validation triggered even though flag is set to false

### ISSUE THREAD

**Issue by ergonlogic** [php-tuf/composer-integration#59]
In `TufValidatedComposerRepository::__construct()`, we only check that the `tuf` flag is set:

```
      if (isset($repoConfig['tuf'])) {
```

This leads to the following also triggering TUF validation, whereas it clearly should not: 

        {   
            "type": "composer",
            "url": "http://packages.ddev.site",
            "tuf": false
        },

**Comment by phenaproxima** [comment]
I guess we could change that `isset()` to `!empty()`, because I agree this is confusing behavior. If you file a PR, @ergonlogic, I'll merge it.

**Comment by phenaproxima** [comment]
Tagging as a good first issue for someone. Although I'd like there to be test coverage, I don't mind writing that if someone has a PR which implements the change.

**Comment by phenaproxima** [comment]
This is long fixed by #83. Closing.
