### ISSUE TITLE
Add php-tuf version to the Composer user agent string

### ISSUE THREAD

**Issue by drumm** [php-tuf/composer-integration#82]
Composer’s user agent string already includes quite a bit of detail about the client, like:

* `Composer/2.5.4 (Darwin; 22.3.0; PHP 8.1.15; streams)`
* `Composer/2.2.21 (Linux; 5.4.0-122-generic; PHP 8.0.19; streams; CI)`

In the long run, the TUF spec will change, and there may be new capabilities we want to take advantage of server-side. If we don’t know what portion of clients have support for something, we are either stuck on only providing the old API or have to make an arbitrary decision in the dark.

As a service provider, I'd like to know what version of php-tuf clients are on.

**Comment by phenaproxima** [comment]
I don't see any way to alter the User-Agent header that Composer sends, without overwriting it completely.

Would a separate header be acceptable? Something like:

```
X-PHP-TUF: $VERSION
```

**Comment by drumm** [comment]
Sure, that looks good!
