### ISSUE TITLE
Tuf\ComposerIntegration\Loader::load declaration is incompatible with upstream GuzzleHttp\Promise\PromiseInterface

### ISSUE THREAD

**Issue by sensespidey** [php-tuf/composer-integration#93]
We're seeing failure to install the composer-integration plugin, due to a mismatch between the upstream GuzzleHttp interface, which presumably has changed. This failure appears on the `main` branch as well, and shows up on the latest CI build: https://github.com/php-tuf/composer-integration/actions/runs/7551008319.

```
- Installing php-tuf/composer-integration (1.0.0-alpha5): Cloning 9eab6300ae55bb0e940783db500a84694f5d7ac7 from cache
PHP Fatal error:  Declaration of Tuf\ComposerIntegration\Loader::load(string $locator, int $maxBytes): Psr\Http\Message\StreamInterface must be compatible with Tuf\Loader\LoaderInterface::load(string $locator, int $maxBytes): GuzzleHttp\Promise\PromiseInterface in /var/www/html/d9-site/vendor/php-tuf/composer-integration/src/Loader.php on line 35
```

FYI This is causing failures in the Rugged tests that make use of this plugin.

**Comment by phenaproxima** [comment]
Fixed in #100.
